version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies"
      - yum update -y
      - amazon-linux-extras enable epel
      - yum install -y epel-release
      - yum install -y gcc SDL2 SDL2_image SDL2_ttf SDL2_mixer
      - pip install pygame networkx
  pre_build:
    commands:
      - echo "Preparing environment"
  build:
    commands:
      - echo "Running tests"
      - python -m unittest discover -s tests
  post_build:
    commands:
      - echo "Build completed successfully"
artifacts:
  files:
    - app.zip
  discard-paths: yes
