version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8  # Adjust as per the environment needs
    commands:
      - echo "Installing dependencies"
      - yum install -y python3-pip
      - pip3 install --upgrade pip
      - pip3 install pygame
      - pip3 install networkx
  pre_build:
    commands:
      - echo "Preparing environment"
      - mkdir -p /opt/resources  # For storing resources like images
      - echo "Ensure required assets like 'coin.png' are present"
  build:
    commands:
      - echo "Running the Python script"
      - python3 final.py  # This will execute the uploaded script
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - '**/*'
  discard-paths: no
